# .github/workflows/production.yml
name: Deploy Production(master branch) to GitHub Pages

on:
  pull_request:
    # Trigger the workflow on pull requests targeting the master branch
    branches:
      - master

  # Trigger the workflow on push events targeting the master branch
  push:
    branches:
      - master

  # Allow manual triggering of the workflow from the Actions tab
  workflow_dispatch:

permissions:
  # Set necessary permissions for GitHub Pages deployment
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-master-branch:
    environment:
      # Define the environment name for deployment
      name: production
      # Set the environment URL dynamically based on the deployment output
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      # Disable CI environment to prevent treating warnings as errors during build
      CI: false
    steps:
      - name: Checkout source code
        # Fetch the latest source code from the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        # Install Node.js to support React build commands
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        # Install all necessary npm packages
        run: npm install

      - name: Build for production
        # Build the React project for production deployment
        run: npm run build

      - name: Disable Jekyll for GitHub Pages
        run: echo > ./build/.nojekyll

      - name: Deploy to gh-pages root
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build
          destination_dir: .
